language: node_js
node_js:
  - 12
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      - libnss3
services:
  - xvfb
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
# before_install:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
install:
  - npm install
  - npm run build
script:
  - nohup npm run ci &
  - sleep 3
  - npm run test
